backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: 'assets/uploads'
collections:
  - name: 'pages'
    label: 'Pages'
    editor:
      preview: false
    files:
      - label: 'Početna'
        name: 'index'
        file: 'index.md'
        fields:
          - { label: 'Naslov', name: 'title', widget: 'string', default: 'Početna' }
          - { label: "Naslovna Pozadinska slika", name: "cover_image", widget: "image", required: true }
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'index' }
          - { label: 'Koncept Naslov', name: 'our_concept_title', widget: "string" }
          - label: "Poziv Na Akciju"
            name: 'free_training'
            widget: object
            collapsed: true
            summary: '{{fields.title}}'
            fields: 
              - { label: "Pozadinska Slika", name: "image", widget: "image" }
              - { label: "Naslov", name: "title", widget: "string", default: "Besplatni probni trening" }
              - { label: "Tekst Dugmeta", name: 'button_text', widget: 'string', default: 'Saznaj više'}
              - { label: 'Gde treba da vodi', name: 'button_url', widgtet: 'string', default: 'membership' }
          - { label: "Naš Tim Naslov", name: our_team_title, widget: 'string' }
          - label: 'Naš Tim'
            name: 'our_team'
            widget: 'list'
            allow_add: true
            label_singular: 'trenera'
            summary: '{{fields.name}} - {{fields.role}}'
            fields: 
              - { label: "Ime i prezime", name: "name", widget: "string" }
              - { label: "Pozicija", name: 'role', widget: 'string'}
              - { label: "Slika", name: "image", widget: "image", required: true }
          - label: 'Članstvo'
            name: 'membership'
            widget: object
            allow_add: false
            summary: '{{fields.title}}'
            fields: 
              - { label: "Slika", name: "image", widget: "image" }
              - { label: "Naslov", name: "title", widget: "string", required: true }
              - { label: "Text", name: 'text', widget: 'markdown', required: false }
          - label: 'Radno vreme'
            name: 'working_hours'
            widget: object
            allow_add: false
            summary: '{{fields.title}}'
            fields: 
              - { label: "Naslov", name: "title", widget: "string", required: true }
              - { label: "Text", name: 'text', widget: 'markdown', required: false }
              - { label: Radno vreme radnim danima, name: working_hours_working_days, widget: 'string', required: true, hint: 'Vreme razdvojiti crticom(-)' }
              - { label: Radno vreme subotom, name: working_hours_weekend, widget: 'string', required: true, hint: 'Vreme razdvojiti crticom(-)' }

      - label: 'O nama'
        name: 'about'
        file: 'about.md'
        fields:
          - { label: 'Naslov', name: 'title', widget: 'string', default: 'O nama' }
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'about-us' }
          - label: 'Sekcije'
            name: 'secitons'
            widget: list
            allow_add: true
            label_singular: Sekciju
            summary: '{{fields.title}}' 
            fields: 
              - { label: "Naslov", name: "title", widget: "string" }
              - { label: "Pocetni text", name: 'text', widget: 'markdown' }
              - { label: "Tekst izmedu slikama", name: 'second-text', widget: 'markdown', required: false  }
              - { label: "Posledni text", name: 'third-text', widget: 'markdown', required: false  }
              - label: "Vrednosti"
                name: "values"
                widget: list
                allow_add: true
                fields: 
                  - { label: "vrednost", name: "value", widget: "string", required: false }
                  - { label: "slika", name: "image", widget: "image", required: false }
                
      
               
      - label: 'Članstvo'
        name: 'membership'
        file: 'membership.md'
        fields: 
          - { label: "Naslov", name: "title", widget: "string", required: true }
          - { label: 'Slika', name: 'image', widget: 'image'}
          - { label: "Tekst ispod naslova", name: 'text', widget: 'markdown', required: false }
          - { label: "Pravinlink naslov", name: "rules", widget: "string", required: true }
          - { label: "Pravilnik tekst", name: 'rules_text', widget: 'markdown', required: true }
          - label: 'Cenovnik'
            name: 'pricelist' 
            widget: 'list'
            summary: '{{fields.title}}'
            fields: 
              - { lable: "Naslov", name: 'title', widget: 'string' }
              - label: "Usluge"
                name: "services"
                widget: "list"
                summary: '{{fields.service}}'
                allow_add: true
                fields: 
                  - { label: "Usluga", name: "service", widget: "string", hint: "Postavi uslugu"}
                  - { label: "Cena", name: "price", widget: "string", hint: "Dodaj cenu"}
              - { lable: "Dodatni opis", name: 'description', widget: 'string' }
          - label: 'Popusti'
            name: 'discounts' 
            widget: 'list'
            summary: '{{fields.title}}'
            fields: 
              - { lable: "Naslov", name: 'title', widget: 'string' }
              - label: "Usluge"
                name: "services"
                widget: "list"
                fields: 
                  - { label: "Usluga", name: "service", widget: "string", hint: "Postavi uslugu"}
              - { lable: "Dodatni opis", name: 'description', widget: 'string', required: false }
          - label: 'PROGRAM LOJALNOSTI'
            name: 'loyalty' 
            widget: 'list'
            summary: '{{fields.title}}'
            fields: 
              - { lable: "Naslov", name: 'title', widget: 'string' }
              - label: "Usluge"
                name: "services"
                widget: "list"
                fields: 
                  - { label: "Vreme", name: "time", widget: "string", hint: "Vreme trajanja"}
                  - { label: "Članarine", name: "membership", widget: "string" }
                  - { label: "Kartica", name: "card", widget: "string" }
                  - { label: "Popust", name: "discount", widget: "string" }
              - label: "Dodatni opisi"
                name: "descriptions"
                widget: "list"
                fields: 
                  - { label: "Opis", name: "description", widget: "string", hint: "Postavi uslugu"}

      - label: 'Vaučer'
        name: 'vaucher'
        file: 'vaucher.md'
        fields: 
          - { label: 'Slika', name: 'image', widget: 'image'}
          - { label: "Poklon vaučer naslov", name: "vaucher_gift_title", widget: "string", required: true }
          - { label: "Poklon vaučer text", name: "vaucher_gift_text", widget: "text", required: true }
          - { label: "Poklon vaučer dugme tekst", name: "vaucher_gift_button", widget: "string", required: true }
          - { label: "Ponude za firme naslov", name: "vaucher_companies_title", widget: "string", required: true }
          - { label: "Ponude za firme", name: "vaucher_companies_text", widget: "text", required: true }
          - { label: "Ponude za firme email", name: "vaucher_companies_email", widget: "string", required: true }
          - label: 'Cenovnik'
            name: 'pricelist' 
            widget: 'list'
            summary: '{{fields.title}}'
            fields: 
              - { lable: "Naslov", name: 'title', widget: 'string' }
              - label: "Usluge"
                name: "services"
                widget: "list"
                summary: '{{fields.service}}'
                allow_add: true
                fields: 
                  - { label: "Usluga", name: "service", widget: "string", hint: "Postavi uslugu"}
                  - { label: "Cena", name: "price", widget: "string", hint: "Dodaj cenu"}
              - { lable: "Dodatni opis", name: 'description', widget: 'string' }
          - label: 'Popusti'
            name: 'discounts' 
            widget: 'list'
            summary: '{{fields.title}}'
            fields: 
              - { lable: "Naslov", name: 'title', widget: 'string' }
              - label: "Usluge"
                name: "services"
                widget: "list"
                fields: 
                  - { label: "Usluga", name: "service", widget: "string", hint: "Postavi uslugu"}
              - { lable: "Dodatni opis", name: 'description', widget: 'string' }
          - label: 'PROGRAM LOJALNOSTI'
            name: 'loyalty' 
            widget: 'list'
            summary: '{{fields.title}}'
            fields: 
              - { lable: "Naslov", name: 'title', widget: 'string' }
              - label: "Usluge"
                name: "services"
                widget: "list"
                fields: 
                  - { label: "Vreme", name: "time", widget: "string", hint: "Vreme trajanja"}
                  - { label: "Članarine", name: "membership", widget: "string" }
                  - { label: "Kartica", name: "card", widget: "string" }
                  - { label: "Popust", name: "discount", widget: "string" }
              - label: "Dodatni opisi"
                name: "descriptions"
                widget: "list"
                summary: '{{fields.description}}'
                allow_add: true
                fields: 
                  - { label: "Opis", name: "description", widget: "string", hint: "Postavi uslugu"}


      - label: Galerija
        name: 'gallery'
        file: 'gallery.md'
        widget: list
        fields: 
          - { label: 'Naslov', name: 'title', widget: 'string', default: 'Glaerija' }
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'gallery' }
          - label: 'Slike'
            name: 'images'
            widget: 'list'
            allow_add: true
            label_singular: "Dodaj sliku"
            summary: '{{fields.alt}}'
            fields:
              - { label: "Alt Tekst", name: "alt", widget: "string" }
              - { label: "Slika", name: "image", widget: "image" }


      - label: 'Kontakt'
        name: contact
        file: contact.md
        widget: list
        summary: '{{fields.title}}'
        fields: 
          - { label: "Naslov", name: "title", widget: "string", required: true }
          - label: 'Radno vreme'
            name: 'working_hours'
            widget: object
            allow_add: false
            summary: '{{fields.title}}'
            fields: 
              - { label: "Naslov", name: "title", widget: "string", required: true }
              - { label: "Text", name: 'text', widget: 'markdown', required: false }
              - { label: Radno vreme radnim danima, name: working_hours_working_days, widget: 'string', required: true, hint: 'Vreme razdvojiti crticom(-)' }
              - { label: Radno vreme subotom, name: working_hours_weekend, widget: 'string', required: true, hint: 'Vreme razdvojiti crticom(-)' }


      - label: 'FAQ'
        name: 'faq'
        file: 'faq.md'
        fields:
          - { label: 'Naslov', name: 'title', widget: 'string', default: 'FAQ - ČESTA PITANJA <br> I ODGOVORI' }
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'faq' }
          - { label: 'Podnaslov', name: 'subtitle', widget: 'string', hint: 'Podnaslov'}
          - label: 'Kategorije'
            name: 'categories' 
            widget: 'list'
            summary: '{{fields.title}}'
            fields: 
              - { lable: "Naslov", name: 'title', widget: 'string', hint: "Ime kategorije"}
              - label: "Pitanja i odgovori"
                name: "questions"
                widget: "list"
                fields: 
                  - { label: "Pitanje", name: "question", widget: "string", hint: "Postavi pitanje"}
                  - { label: "Odgovor", name: "answer", widget: "markdown", hint: "Dodaj odgovor"}

      - label: 'Naš tim'
        name: 'team'
        file: 'team.md'
        fields:
        - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'team' }
        - { label: 'Naslov', name: 'title', widget: 'string' }
        - { label: 'Kratak opis', name: short_description, widget: 'text', required: false}
        - label: 'Naš Tim'
          name: 'our_team'
          widget: 'list'
          allow_add: true
          label_singular: 'trenera'
          summary: '{{fields.name}} - {{fields.role}}'
          fields: 
            - { label: 'Prikazi na početnoj strani', name: 'show_on_homepage',  widget: 'boolean', default: false, required: false }
            - { label: "Slika", name: "image", widget: "image", required: true }
            - { label: "Ime i prezime", name: "name", widget: "string" }
            - { label: "Pozicija", name: 'role', widget: 'string'}
            - { label: "Opis", name: 'description', widget: 'text', required: false}
      


  - name: 'concepts'
    label: 'Trening Koncepti'
    folder: '/concepts'
    create: true
    file: '{{fields.layout}}.md'
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'single_concept' }
      - { label: 'Ime Koncepta', name: 'title', widget: 'string' }
      - { label: 'Redosled', name: 'custom_order', widget: number, default: 30 }
      - { label: 'Ukratko o konceptu', name: short_description, widget: 'text', required: false}
      - { label: 'Prikazi na početnoj strani', name: 'show_on_homepage',  widget: 'boolean', default: false, required: false }
      - { laabel: 'Youtube video', name: 'youtube_src', widget: 'string', required: false }
      - label: "Galerija"
        name: "gallery"
        widget: 'list'
        collapsed: false
        allow_add: true
        label_singular: "Dodaj sliku"
        field: { label: Slika, name: image, widget: image } 
      - { label: "Tekst ispod naslova", name: 'subtitle', widget: 'text', required: false }           
      - { label: "Naša misija naslov", name: 'our_mission_title', widget: 'string', default: 'Naša misija', required: false }           
      - label: "Naša misija"
        name: 'our_mission'
        widget: "list"
        collapsed: false
        allow_add: true
        label_singular: "Dodaj sekciju"
        fields: 
          - { label: 'Naslov', name: 'title', widget: 'string' }
          - { label: 'Tekst', name: 'description', widget: 'text' }
          - { label: 'Slika', name: 'image', widget: "image" }
      - { label: "Slika pored Cenovnika", name: 'price_image', widget: "image", default: '/assets/uploads/gym2.jpeg' }
      - label: "Cenovnik"
        name: 'prices'
        widget: 'list'
        collapsed: false
        label_singular: "Dodaj cenovnu kategoriju"
        summary: '{{fields.service}}: {{fields.price}}'
        fields: 
          - { label: "Usluga", name: "service", widget: "string" }
          - { label: "Cena", name: "price", widget: "string" }
      - { label: "Cenovnik - dodatno objašnjenje", name: 'additional_description', widget: 'string', hint: "Tekst ispod cenovnika", required: false }
      - { label: "Pravilnik Naslov", name: 'rule_book_title', widget: 'string', required: false }
      - { label: "Pravilnik", name: 'rule_book', widget: 'markdown', required: false }


  
