backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: 'assets/uploads'
collections:
  - name: 'pages'
    label: 'Pages'
    editor:
      preview: false
    files:
      - label: 'Početna'
        name: 'index'
        file: 'index.md'
        fields:
          - { label: 'Naslov', name: 'title', widget: 'string', default: 'Pocetna' }
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'index' }
      - label: 'O nama'
        name: 'about'
        file: 'about.md'
        fields:
          - { label: 'Naslov', name: 'title', widget: 'string', default: 'O namaa' }
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'about-us' }
      - label: 'FAQ'
        name: 'faq'
        file: 'faq.md'
        fields:
          - { label: 'Naslov', name: 'title', widget: 'string', default: 'FAQ - ČESTA PITANJA <br> I ODGOVORI' }
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'faq' }
          - { label: 'Podnaslov', name: 'subtitle', widget: 'string', hint: 'Podnaslov'}
          - label: 'Kategorije'
            name: 'categories' 
            widget: 'list'
            summary: '{{fields.title}}'
            fields: 
              - { lable: "Naslov", name: 'title', widget: 'string', hint: "Ime kategorije"}
              - label: "Pitanja i odgovori"
                name: "questions"
                widget: "list"
                fields: 
                  - { label: "Pitanje", name: "question", widget: "string", hint: "Postavi pitanje"}
                  - { label: "Odgovor", name: "answer", widget: "text", hint: "Dodaj odgovor"}



  - name: 'concepts'
    label: 'Trening Koncepti'
    folder: '_posts/concepts'
    create: true
    file: '{{fields.layout}}.md'
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'string', default: 'concept' }
      - { label: 'Naslov', name: 'title', widget: 'string' }
      - label: "Naša misija"
        name: 'our_mission'
        widget: "object"
        summary: '{{fields.title}}'
        fields: 
          - { label: 'Naslov', name: 'title', widget: 'string' }
          - { label: 'Tekst', name: 'description', widget: 'text' }
          - { label: 'Slika', name: 'image', widget: "image", choose_url: true }
      - label: "Cenovnik"
        name: 'prices'
        widget: 'list'
        collapsed: false
        summary: '{{ fields.title }}'
        fields: 
          - { label: "Usluga", name: "service", widget: "string" }
          - { label: "Cena", name: "price", widget: "string" }
      - { label: "Cenovnik - dodatno objašnjenje", name: 'additional_description', widget: 'string' }


