backend:
  repo: parkic/sinergija
  branch: main # Branch to update (optional; defaults to master)
  base_url: sinergija.vercel.app
media_folder: 'assets/uploads'
collections:
  - name: 'pages'
    label: 'Pages'
    editor:
      preview: false
    files:
      - label: 'Početna'
        name: 'index'
        file: 'index.md'
        fields:
          - { label: 'Naslov', name: 'title', widget: 'string', default: 'Početna' }
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'index' }
          - { label: 'Koncept Naslov', name: 'our_concept_title', widget: "string" }
          - label: 'Naš Tim'
            name: 'our_team'
            widget: 'list'
            allow_add: true
            label_singular: 'trenera'
            summary: '{{fields.name}} - {{fields.role}}'
            fields: 
              - { label: "Ime i prezime", name: "name", widget: "string" }
              - { label: "Pozicija", name: 'role', widget: 'string'}
              - { label: "Slika", name: "image", widget: "image", required: true }
          - label: 'Članstvo'
            name: 'membership'
            widget: object
            allow_add: false
            summary: '{{fields.title}}'
            fields: 
              - { label: "Naslov", name: "title", widget: "string", required: true }
              - { label: "Text", name: 'text', widget: 'markdown', required: false }
          - label: 'Radno vreme'
            name: 'working_hours'
            widget: object
            allow_add: false
            summary: '{{fields.title}}'
            fields: 
              - { label: "Naslov", name: "title", widget: "string", required: true }
              - { label: "Text", name: 'text', widget: 'markdown', required: false }
              - { label: Početak radnog vremena radnim danima, name: start_hours_working_days, widget: 'string', required: true }
              - { label: Kraj radnog vremena radnim danima, name: end_hours_working_days, widget: 'string', required: true }
              - { label: Početak radnog vremena vikendom, name: start_hours_weekend, widget: 'string', required: true }
              - { label: Poceatk radnog vremena vikendom, name: end_hours_weekend, widget: 'string', required: true }

      - label: 'O nama'
        name: 'about'
        file: 'about.md'
        fields:
          - { label: 'Naslov', name: 'title', widget: 'string', default: 'O nama' }
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'about-us' }
          - label: 'Sekcije'
            name: 'secitons'
            widget: list
            allow_add: true
            label_singular: Sekciju
            summary: '{{fileds.title}}'
            fields: 
              - { label: "Naslov", name: "title", widget: "string" }
              - { label: "Tekst", name: 'text', widget: 'markdown' }

      - label: 'Članstvo'
        name: 'membership'
        file: 'membership.md'
        fields: 
          - { label: "Naslov", name: "title", widget: "string", required: true }
          - { label: 'Slika', name: 'image', widget: 'image'}
          - { label: "Tekst ispod naslova", name: 'text', widget: 'markdown', required: false }
          - { label: "Pravinlink naslov", name: "rules", widget: "string", required: true }
          - { label: "Pravilnik tekst", name: 'rules_text', widget: 'markdown', required: true }


      - label: 'Vaučer'
        name: 'vaucher'
        file: 'vaucher.md'
        fields: 
          - { label: 'Slika', name: 'image', widget: 'image'}
          - { label: "Poklon vaučer text", name: "vaucher_gift_text", widget: "text", required: true }
          - { label: "Ponude za firme", name: "vaucher_companies_text", widget: "text", required: true }
          - label: 'Cenovnik (max 4)'
            name: 'pricing'
            widget: list
            allow_add: true
            summary: '{{fields.title}}'
            fileds: 
              - { label: "Naslov", name: "title", widget: "string", required: true }
              - label: 'Pojedinacne stavke'
                widget: list
                allow_add: true
                summary: '{{fields.name}}'
                fields: 
                  - { label: "Ime", name: "name", widget: "string", required: true }
                  - { label: "Cena", name: "price", widget: "string", required: false }
              - { label: "Dodatni tekst", name: "additional_text", widget: "string", required: false }

      - label: Galerija
        name: 'galery'
        file: 'galery.md'
        widget: list
        fields: 
          - { label: 'Naslov', name: 'title', widget: 'string', default: 'Glaerija' }
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'galery' }
          - label: 'Slike'
            name: 'images'
            widget: 'list'
            allow_add: true
            label_singular: "Dodaj sliku"
            summary: '{{fields.alt}}'
            fields:
              - { label: "Alt Tekst", name: "alt", widget: "string" }
              - { label: 'Prikazi u sekcijama po stranama', name: 'show_on_cta', widget: 'boolean', default: false, required: false}
              - { label: "Slika", name: "image", widget: "image" }


      - label: 'Kontakt'
        name: contact
        file: contact.md
        widget: list
        summary: '{{fields.title}}'
        fields: 
          - { label: "Naslov", name: "title", widget: "string", required: true }
          - { label: "Text", name: 'text', widget: 'markdown', required: false }
          - { label: Početak radnog vremena radnim danima, name: start_hours_working_days, widget: 'string', required: true }
          - { label: Kraj radnog vremena radnim danima, name: end_hours_working_days, widget: 'string', required: true }
          - { label: Početak radnog vremena vikendom, name: start_hours_weekend, widget: 'string', required: true }
          - { label: Poceatk radnog vremena vikendom, name: end_hours_weekend, widget: 'string', required: true }


      - label: 'FAQ'
        name: 'faq'
        file: 'faq.md'
        fields:
          - { label: 'Naslov', name: 'title', widget: 'string', default: 'FAQ - ČESTA PITANJA <br> I ODGOVORI' }
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'faq' }
          - { label: 'Podnaslov', name: 'subtitle', widget: 'string', hint: 'Podnaslov'}
          - label: 'Kategorije'
            name: 'categories' 
            widget: 'list'
            summary: '{{fields.title}}'
            fields: 
              - { lable: "Naslov", name: 'title', widget: 'string', hint: "Ime kategorije"}
              - label: "Pitanja i odgovori"
                name: "questions"
                widget: "list"
                fields: 
                  - { label: "Pitanje", name: "question", widget: "string", hint: "Postavi pitanje"}
                  - { label: "Odgovor", name: "answer", widget: "markdown", hint: "Dodaj odgovor"}
      


  - name: 'concepts'
    label: 'Trening Koncepti'
    folder: '/concepts'
    create: true
    file: '{{fields.layout}}.md'
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'single_concept' }
      - { label: 'Ime Koncepta', name: 'title', widget: 'string' }
      - label: "Ukratko o konceptu"
        name: 'short_description'
        widget: 'list'
        allow_add: false
        fileds: 
          - { label: 'Tekst', name: 'text', widget: 'text', required: false}
          - { label: 'Prikazi na početnoj strani', name: 'show_on_homepage',  widget: 'boolean', default: false, required: false }
      - label: "Galerija"
        name: "galery"
        widget: 'list'
        collapsed: false
        allow_add: true
        label_singular: "Dodaj sliku"
        field: { label: Slika, name: image, widget: image } 
      - { label: "Tekst ispod naslova", name: 'subtitle', widget: 'text', required: false }           
      - label: "Naša misija"
        name: 'our_mission'
        widget: "list"
        collapsed: false
        allow_add: true
        label_singular: "Dodaj sekciju"
        fields: 
          - { label: 'Naslov', name: 'title', widget: 'string' }
          - { label: 'Tekst', name: 'description', widget: 'text' }
          - { label: 'Slika', name: 'image', widget: "image" }
      - { label: "Slika pored Cenovnika", name: 'price_image', widget: "image" }
      - label: "Cenovnik"
        name: 'prices'
        widget: 'list'
        collapsed: false
        label_singular: "Dodaj cenovnu kategoriju"
        summary: '{{fields.service}}: {{fields.price}}'
        fields: 
          - { label: "Usluga", name: "service", widget: "string" }
          - { label: "Cena", name: "price", widget: "string" }
      - { label: "Cenovnik - dodatno objašnjenje", name: 'additional_description', widget: 'string', hint: "Tekst ispod cenovnika", required: false }
      - { label: "Pravilnik", name: 'rule_book', widget: 'markdown', required: false }



